version: '3.7'

services:
  app:
    image: 'regyl/testing-system:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - TestingSystemDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testingsystem
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=SomeUselessPassword02
    ports:
      - '8080:8080'

  TestingSystemDB:
    image: 'postgres:13.3'
    container_name: TestingSystemDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SomeUselessPassword02
      - POSTGRES_DB=testingsystem